apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argus.fullname" . }}-config
  labels:
    {{- include "argus.labels" . | nindent 4 }}
data:
  argus.json: |
    {{- mustToJson .Values.config.argus_json | nindent 4 }}
  base-policy.json: |
{{ .Values.config.base_policy | indent 4 }}
