{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "argus.fullname" . }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "argus.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.service.pgProxyPort }}
        - port: {{ .Values.service.mysqlProxyPort }}
    {{- if .Values.config.argus_json.admin.enabled }}
    - ports:
        - port: {{ .Values.service.adminPort }}
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ops
    {{- end }}
    {{- if .Values.config.argus_json.metrics.enabled }}
    - ports:
        - port: {{ .Values.service.metricsPort }}
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
    {{- end }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - ports:
        - port: 443
          protocol: TCP
      to:
        - ipBlock:
            cidr: 0.0.0.0/0
    {{- range .Values.networkPolicy.egressCIDRs }}
    - to:
        - ipBlock:
            cidr: {{ . }}
    {{- end }}
    {{- range .Values.networkPolicy.siemEgressCIDRs }}
    - ports:
        - port: 443
          protocol: TCP
      to:
        - ipBlock:
            cidr: {{ . }}
    {{- end }}
{{- end }}
